& /0000

BATCH >

; Lista para salvar os getdatas
BATCH_GD_LIST $ =0
	JP BATCH_GD_INI1
	JP /0000

; Cosntantes
BATCH_CONST_2  K /2
BATCH_CONST_LD K /8000
BATCH_CONST_GD K /D000
BATCH_CONST_MM K /9000

; 
BATCH_CONST_SLASHSLASH K /2F2F
BATCH_CONST_JB         K /4A42
BATCH_CONST_EOL        K /0D0A
BATCH_CONST_DU         K /4455
BATCH_CONST_LU         K /4C55
BATCH_CONST_SLASHSTAR  K /2F2A

;=======================================
; Função para executar o batch
;=======================================
; Variáveis
BATCH_UL K /0000
BATCH_VAR_CMD K /0000
; Função de batch
BATCH K /0000
	
	; Cria a lista de instruções GD
	LD BATCH_UL
	+  BATCH_CONST_GD
	MM BATCH_GD_INI1
	MM BATCH_GD_INI2
	MM BATCH_GD_INIEOL
	MM BATCH_GD_CMD1

;------------------------------
; Lê o //JB
;------------------------------
BATCH_READ_INI1 $ =0
	BATCH_GD_INI1 K /0000
	- BATCH_CONST_SLASHSLASH
	JZ BATCH_READ_INI2
	LV /001
	JP BATCH_ERROR

BATCH_READ_INI2
	BATCH_GD_INI2 K /0000
	- BATCH_CONST_JB
	JZ BATCH_READ_INIEOL
	LV /001
	JP BATCH_ERROR
BATCH_READ_INIEOL
	BATCH_GD_INIEOL K /0000
	- BATCH_CONST_EOL
	JZ BATCH_READ_INIEND
	LV /001
	JP BATCH_ERROR
BATCH_READ_INIEND $ =0

;------------------------------
; Lê o Comando
;------------------------------
BATCH_READ_CMD1 $ =0
	BATCH_GD_CMD1 K /0000
	- BATCH_CONST_SLASHSLASH
	JZ BATCH_READ_CMD2
	LV /002
	JP BATCH_ERROR

BATCH_READ_CMD2
	BATCH_GD_INI2 K /0000
	MM BATCH_VAR_CMD
	- BATCH_CONST_JB
	JZ BATCH_READ_INIEOL
	LV /001
	JP BATCH_ERROR
BATCH_READ_CMDEOL
	BATCH_GD_INIEOL K /0000
	- BATCH_CONST_EOL
	JZ BATCH_READ_INIEND
	LV /001
	JP BATCH_ERROR
BATCH_READ_INIEND $ =0

; Processa o inicio do batch
BATCH_ERROR $ =0
	OS /0EE
	JP BATCH_END

; 
BATCH_END $ =0
	RS BATCH

# BATCH